Namespaces in xml document
None
Document generating code
AjpesDokument = etree.Element(AjpesDokument, nsmap=ns)
Ident = add_element_data(Ident, root_element)
add_element_data(Datum, Ident)
add_element_data(Ura, Ident)
add_element_data(NacinPredlozitve, Ident)
add_element_data(VsePravice, Ident)
Zavezanec = add_element_data(Zavezanec, root_element)
OsnovniPodatki = add_element_data(OsnovniPodatki, Zavezanec)
add_element_data(MaticnaStevilka, OsnovniPodatki)
add_element_data(DavcnaStevilka, OsnovniPodatki)
add_element_data(Dejavnost, OsnovniPodatki)
add_element_data(Ime, OsnovniPodatki)
add_element_data(Racun, OsnovniPodatki)
add_element_data(Pogodba, OsnovniPodatki)
add_element_data(Sedez, OsnovniPodatki)
add_element_data(OdgovornaOseba, OsnovniPodatki)
add_element_data(TelefonskaStevilka, OsnovniPodatki)
Obrazci = add_element_data(Obrazci, Zavezanec)
Obrazec = add_element_data(Obrazec, Obrazci)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
Aop = add_element_data(Aop, Obrazec)
add_element_data(P, Aop)
