'name' :'Mentis  MODULE_NAME',
'version' :'1.0',
'author' :'Mentis d.o.o',
'website' :'http://www.odoo.si',
'category' :'MODULE_CATEGORY',
'description' :'""" MODULE_DESCRIPTION """',
'application' :False,
'depends' :[],
'data' :[],
'installable' :True,
'active' :False,
